@host = localhost:8089/api

@api = expenses

### Get all
# @name request 
GET http://{{host}}/{{api}}

#@id = {{request.response.body.0._id}}

### Get by Id
@id = no_id
GET http://{{host}}/{{api}}/{{id}}

### Delete by Id
DELETE http://{{host}}/{{api}}/{{id}}

### Update by Id
PUT http://{{host}}/{{api}}/{{id}}

{}